### ISSUE TITLE
System groups doesn't seem to work with this

### ISSUE THREAD

**Issue by magenbrot** [custom-cards/group-card#1]
Hi,
I tried to use the card with the following configuration. group.all_automations is a predefined system group.

```
      - type: custom:group-card
        card:
          type: entities
          title: Alle Automatisierungen
          group: group.all_automations
```

The card just shows 'Please specify a group'.

**Comment by iantrich** [comment]
you have group indented too far. Try this

```yaml
      - type: custom:group-card
        group: group.all_automations
        card:
          type: entities
          title: Alle Automatisierungen
````
