### ISSUE TITLE
Ability to hide header toggle

### ISSUE THREAD

**Issue by yuvalabou** [custom-cards/group-card#3]
like in the entities card -
show_header_toggle: false

**Comment by ceesvanegmond** [comment]
@yuvalabou +1

**Comment by soffes** [comment]
You can do it like this:

```yaml
  - type: custom:group-card
    card:
      type: entities
      title: Batteries
      show_header_toggle: false
    group: group.all_batteries
```
